Add Hazy theme
Gerg-L/spicetify-nix pull request #232
Opened 2024-10-01 23:22 UTC by SharpStormGames

adds [hazy](https://github.com/Astromations/Hazy)

2024-10-01 23:51 UTC, gigamonster256 commented
I’m sure adding this to the THEMES.md doc would be appreciated

2024-10-02 00:29 UTC, SharpStormGames commented
apologies, it is added now.

2024-10-02 13:27 UTC, Gerg-L requested changes
This then I'll merge

2024-10-02 13:27 UTC, Gerg-L commented on pkgs/themes.nix
> +      overwriteAssets = false;
```suggestion
```
appendName was removed, the other three are set to the defaults and not needed

2024-10-02 13:28 UTC, Gerg-L commented
Thanks @gigamonster256

2024-10-02 23:18 UTC, merged

2024-10-02 23:19 UTC, Gerg-L commented
Thanks for contributing!